# Generated by Django 3.2 on 2021-04-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemcompo',
            old_name='chemical',
            new_name='element',
        ),
    ]
